### ISSUE TITLE
idk why this happened. undefined symbol: BIO_meth_set_puts

### ISSUE THREAD

**Issue by ynckz** [OEvortex/Webscout#17]
```
> webscout --help

Traceback (most recent call last):
  File "/home/ynckz/.local/bin/webscout", line 5, in <module>
    from webscout.webai import main
  File "/home/ynckz/.local/lib/python3.12/site-packages/webscout/__init__.py", line 3, in <module>
    from .webscout_search import WEBS
  File "/home/ynckz/.local/lib/python3.12/site-packages/webscout/webscout_search.py", line 15, in <module>
    import primp  # type: ignore
    ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/primp/__init__.py", line 1, in <module>
    from .primp import *
ImportError: /usr/lib/python3.12/site-packages/primp/primp.abi3.so: undefined symbol: BIO_meth_set_puts
```

**Comment by Processori7** [comment]
Hello, you can try this:
python --help webscout
or
python -h webscout
So, if I use:
webscout --help, then I received
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\Users\Igory\Desktop\AnsiUi2\.venv\Scripts\webscout.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'webscout.webai'

**Comment by djfaizp** [comment]
Have you tried 

python -m webscout --help
